#!/usr/bin/env python3


import sys
import os


class Units:
    project_folder = ""
    project_file = ""
    unit_args = []
    unit_test = {}

    def __init__(self, filename):
        self.filename = filename
        fp = open(filename, "r")
        self.file = fp.read().split("\n")
        fp.close()

    def parse_file(self):
        self.project_folder = self.file[0].split("project_name=")[1]
        self.project_file = self.file[1].split("files=")[1]

        for i in range(0, len(self.file)):
            if self.file[i].find("args=") == 0 and self.file[i + 1] == "START":
                arg = self.file[i].split("args=")[1]
                self.unit_args.append(arg)
                self.unit_test[arg] = []
                i += 2
                output = ""
                while self.file[i] != "END":
                    if self.file[i] == "#-#-#-#-#-#":
                        self.unit_test[arg].append(output)
                        output = ""
                    else:
                        output += self.file[i]
                    i += 1

        for args in self.unit_args:
            for elem in self.unit_test[args]:
                print(elem)
            print("--------")
        print(self.unit_test)
        print(self.project_folder)
        print(self.project_file)


class Student:
    def __init__(self, folder):
        self.folder = folder
        self.mark = 0

    def open_folder(self):
        print(self.folder)

    def correction(self):
        print(self.folder)
        print("Final mark :", self.mark, "\n")


# Core


def core():
    path = sys.argv[2]

    units = Units(sys.argv[1])
    units.parse_file()

    folders = os.listdir(path)
    for name in folders:
        student = Student(name)


# Helper


def print_help():
    print("USAGE:", "\n")
    print("\t./moulinette file_responses.txt folder", "\n")
    print("Made by web@cadémie Strasbourg ❤️")


if __name__ == '__main__':
    if len(sys.argv) == 3:
        core()
    else:
        print_help()

